services:
  mongo:
    image: mongo:latest
    container_name: medical_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  python_migration:
    build:
      context: .       # Dockerfile est ici
    container_name: migration_script
    depends_on:
      - mongo
    volumes:
      - ../MedicalMigration/dataset:/app/dataset
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=medical_db
      - MONGO_COLL=patients
      - CSV_PATH=/app/dataset/healthcare_dataset.csv
    command: ["python", "scripts/migrate_to_mongo.py"]

volumes:
  mongo_data: {}
