name: CI - Tests unitaires

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    container: python:3.11-slim

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation des dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécution des tests unitaires
        working-directory: /github/workspace/MedicalMigration
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v
